name: Actions Lint

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26.4

      - name: Install linters
        run: |
          go install github.com/suzuki-shunsuke/ghalint/cmd/ghalint@v1.5.6
          go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

      - name: Run ghalint
        run: ghalint run

      - name: Run actionlint
        run: actionlint
